apiVersion: v2
name: tubearchivist
version: 0.0.4
sources:
  - https://github.com/tubearchivist/tubearchivist
  - https://github.com/alexlebens/helm-charts/charts/tubearchivist
dependencies:
  - name: tubearchivist
    version: 0.0.4
    repository: http://alexlebens.github.io/helm-charts
  - name: tubearchivist-to-jellyfin
    version: 0.0.1
    repository: http://alexlebens.github.io/helm-charts    
appVersion: v0.4.6
