apiVersion: v1
kind: PersistentVolume
metadata:
  name: kyoo-nfs-storage
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kyoo-nfs-storage
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.persistence.nfsPath }}
    server: {{ .Values.persistence.nfsServer }}
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
