apiVersion: v2
name: authentik
version: 1.0.0
sources:
  - https://github.com/goauthentik/authentik
  - https://github.com/goauthentik/helm
  - https://github.com/alexlebens/helm-charts/charts/postgres-cluster
dependencies:
  - name: authentik
    version: 2024.4.0
    repository: https://charts.goauthentik.io/
  - name: postgres-cluster
    alias: postgres-16-cluster
    version: 2.4.2
    repository: http://alexlebens.github.io/helm-charts
  - name: app-template
    alias: cloudflared
    repository: https://bjw-s.github.io/helm-charts/
    version: 3.1.0
appVersion: "2024.2.3"
