apiVersion: v2
name: authentik
version: 1.0.0
sources:
  - https://github.com/goauthentik/authentik
  - https://github.com/goauthentik/helm
  - https://github.com/alexlebens/helm-charts/charts/postgres-cluster
dependencies:
  - name: authentik
    version: 2024.2.2
    repository: https://charts.goauthentik.io/
  - name: postgres-cluster
    alias: postgres-16-cluster
    version: 2.3.6
    repository: http://alexlebens.github.io/helm-charts    
appVersion: "2024.2.2"
