apiVersion: v2
name: authentik
version: 0.0.3
sources:
  - https://github.com/goauthentik/authentik
  - https://github.com/goauthentik/helm
  - https://github.com/alexlebens/helm-charts/charts/postgres-cluster
dependencies:
  - name: authentik
    version: 2024.2.2
    repository: https://charts.goauthentik.io/
  - name: postgres-cluster
    version: 0.2.2
    repository: http://alexlebens.github.io/helm-charts
appVersion: "2024.2.2"
