authentik:
  global:
    env:
      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-key-secret
            key: key
      - name: AUTHENTIK_POSTGRESQL__HOST
        valueFrom:
          secretKeyRef:
            name: postgresql-authentik-cluster-app
            key: host
      - name: AUTHENTIK_POSTGRESQL__NAME
        valueFrom:
          secretKeyRef:
            name: postgresql-authentik-cluster-app
            key: dbname
      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: postgresql-authentik-cluster-app
            key: user
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-authentik-cluster-app
            key: password
  server:
    name: server
    replicas: 1
    volumes:
      - name: custom-css
        configMap:
          name: authentik-custom-css
    volumeMounts:
      - name: custom-css
        mountPath: /web/dist/custom.css
        subPath: custom.css
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      ingressClassName: traefik
      hosts:
        - authentik.alexlebens.net
      tls:
        - secretName: authentik-secret-tls
          hosts:
            - authentik.alexlebens.net
  worker:
    name: worker
    replicas: 1
  prometheus:
    rules:
      enabled: true
  postgresql:
    enabled: false
  redis:
    enabled: true
postgres-cluster:
  cluster:
    name: cl01tl
    image:
      repository: ghcr.io/cloudnative-pg/postgresql
      tag: 16.2
    instances: 2
    storage:
      data:
        storageClass: ceph-block
        size: 10Gi
      wal:
        storageClass: ceph-block
        size: 2Gi
  bootstrap:
    recoveryEnabled: false
    recoveryIndex: 1
    endpointURL: https://nyc3.digitaloceanspaces.com
    bucket: alexlebens-net
  backup:
    backupEnabled: true
    backupIndex: 1
    endpointURL: https://nyc3.digitaloceanspaces.com
    bucket: alexlebens-net
postgres-16-cluster:
  mode: replica
  kubernetesClusterName: cl01tl
  cluster:
    walStorage:
      storageClass: local-path
    storage:
      storageClass: local-path
    monitoring:
      enabled: true
      prometheusRule:
        enabled: false
  replica:
    importType: microservice
    importDatabases:
      - app
    externalCluster:
      connectionParameters:
        host: postgresql-authentik-cluster-rw
        user: app
        dbname: app
      password:
        name: postgresql-authentik-cluster-app
        key: password
  backup:
    enabled: true
    endpointURL: https://nyc3.digitaloceanspaces.com
    endpointBucket: alexlebens-net
    endpointCredentials: authentik-postgresql-16-cluster-backup-secret
    backupIndex: 1
    retentionPolicy: "14d"
