apiVersion: v2
name: traefik
version: 1.0.0
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
dependencies:
  - name: traefik
    version: 28.0.0
    repository: https://traefik.github.io/charts
appVersion: v2.11.0
