apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.application.source.repo }}
    targetRevision: {{ .Values.application.source.revision }}
    path: {{ .Values.application.source.path }}
  destination:
    name: in-cluster
    namespace: {{ .Release.Namespace }}
  revisionHistoryLimit: 3
  syncPolicy:
    {{- toYaml .Values.application.syncPolicy | nindent 4 }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.application.cilium.source.repo }}
    targetRevision: {{ .Values.application.cilium.source.revision }}
    path: {{ .Values.application.cilium.source.path }}
  destination:
    name: in-cluster
    namespace: {{ .Values.application.cilium.namespace }}
  revisionHistoryLimit: 3
  syncPolicy:
    {{- toYaml .Values.application.cilium.syncPolicy | nindent 4 }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.application.metricsServer.source.repo }}
    targetRevision: {{ .Values.application.metricsServer.source.revision }}
    path: {{ .Values.application.metricsServer.source.path }}
  destination:
    name: in-cluster
    namespace: {{ .Values.application.metricsServer.namespace }}
  revisionHistoryLimit: 3
  syncPolicy:
    {{- toYaml .Values.application.metricsServer.syncPolicy | nindent 4 }}
