apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.application.stack.source.repo }}
    targetRevision: {{ .Values.application.stack.source.revision }}
    path: "{{ .Values.git.path }}/{{ .Values.application.stack.source.path }}"
  destination:
    name: in-cluster
    namespace: {{ .Values.application.stack.namespace }}
  revisionHistoryLimit: 3
  syncPolicy:
    {{- toYaml .Values.application.stack.syncPolicy | nindent 4 }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.application.cilium.source.repo }}
    targetRevision: {{ .Values.application.cilium.source.revision }}
    path: "{{ .Values.git.path }}/{{ .Values.application.cilium.source.path }}"
  destination:
    name: in-cluster
    namespace: {{ .Values.application.cilium.namespace }}
  revisionHistoryLimit: 3
  syncPolicy:
    {{- toYaml .Values.application.cilium.syncPolicy | nindent 4 }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.application.metricsServer.source.repo }}
    targetRevision: {{ .Values.application.metricsServer.source.revision }}
    path: "{{ .Values.git.path }}/{{ .Values.application.metricsServer.source.path }}"
  destination:
    name: in-cluster
    namespace: {{ .Values.application.metricsServer.namespace }}
  revisionHistoryLimit: 3
  syncPolicy:
    {{- toYaml .Values.application.metricsServer.syncPolicy | nindent 4 }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.application.kubeletServingCertApprover.source.repo }}
    targetRevision: {{ .Values.application.kubeletServingCertApprover.source.revision }}
    path: "{{ .Values.git.path }}/{{ .Values.application.kubeletServingCertApprover.source.path }}"
  destination:
    name: in-cluster
    namespace: {{ .Values.application.kubeletServingCertApprover.namespace }}
  revisionHistoryLimit: 3
  syncPolicy:
    {{- toYaml .Values.application.kubeletServingCertApprover.syncPolicy | nindent 4 }}
