rocketchat:
  replicaCount: 1
  extraEnv:
    - name: ROOT_URL
      value: http://chat.alexlebens.net
    - name: PORT
      value: 80
  extraSecret: rocketchat-config-secret
  existingMongodbSecret: rocketchat-mongodb-uri-secret
  mongodb:
    enabled: false
  persistence:
    enabled: true
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 8Gi
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    path: /
    tls:
      - hosts:
          - chat.alexlebens.net
        secretName: rocketchat-secret-tls
    federation:
      serveWellKnown: true
  prometheusScraping:
    enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
mongodb:
  architecture: replicaset
  auth:
    enabled: true
    rootUser: admin
    usernames:
      - rocketchat
    databases:
      - rocketchat
    existingSecret: rocketchat-mongodb-auth-secret
  initdbScriptsConfigMap: rocketchat-mongodb-fix-clustermonitor-role-configmap
  replicaCount: 3
  service:
    portName: mongodb
    ports:
      mongodb: 27017
  persistence:
    enabled: true
    name: rocketchat-mongodb-data
    storageClass: ceph-block
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  backup:
    enabled: true
    cronjob:
      schedule: "@daily"
      storage:
        storageClass: nfs-client
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        mountPath: /backup/mongodb
  volumePermissions:
    enabled: true
  arbiter:
    enabled: true
  metrics:
    enabled: true
    compatibleMode: false
    serviceMonitor:
      enabled: true
      interval: 30s
    prometheusRule:
      enabled: true
