apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rocketchat-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/admin
        metadataPolicy: None
          property: ADMIN_USERNAME
    - secretKey: ADMIN_NAME
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/admin
          metadataPolicy: None
          property: ADMIN_NAME
    - secretKey: ADMIN_PASS
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/admin
          metadataPolicy: None
          property: ADMIN_PASS
    - secretKey: ADMIN_EMAIL
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/admin
          metadataPolicy: None
          property: ADMIN_EMAIL
    - secretKey: Accounts_OAuth_Custom_clientId
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /authentik/oidc/rocketchat
          metadataPolicy: None
          property: client
    - secretKey: Accounts_OAuth_Custom_clientSecret
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /authentik/oidc/rocketchat
          metadataPolicy: None
          property: secret
    - secretKey: Accounts_OAuth_Custom_enabled
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: enabled
    - secretKey: Accounts_OAuth_Custom_accessTokenParam
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: accessTokenParam
    - secretKey: Accounts_OAuth_Custom_authorizePath
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: authorizePath
    - secretKey: Accounts_OAuth_Custom_buttonColor
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: buttonColor
    - secretKey: Accounts_OAuth_Custom_buttonLabelColor
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: buttonLabelColor
    - secretKey: Accounts_OAuth_Custom_buttonLabelText
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: buttonLabelText
    - secretKey: Accounts_OAuth_Custom_channelsMap
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: channelsMap
    - secretKey: Accounts_OAuth_Custom_emailField
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: emailField
    - secretKey: Accounts_OAuth_Custom_groupsClaim
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: groupsClaim
    - secretKey: Accounts_OAuth_Custom_identityPath
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: identityPath
    - secretKey: Accounts_OAuth_Custom_identityTokenSentVia
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: identityTokenSentVia
    - secretKey: Accounts_OAuth_Custom_keyField
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: keyField
    - secretKey: Accounts_OAuth_Custom_loginStyle
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: loginStyle
    - secretKey: Accounts_OAuth_Custom_mergeRoles
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: mergeRoles
    - secretKey: Accounts_OAuth_Custom_mergeUsers
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: mergeUsers
    - secretKey: Accounts_OAuth_Custom_nameField
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: nameField
    - secretKey: Accounts_OAuth_Custom_rolesClaim
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: rolesClaim
    - secretKey: Accounts_OAuth_Custom_scope
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: scope
    - secretKey: Accounts_OAuth_Custom_serverURL
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: serverURL
    - secretKey: Accounts_OAuth_Custom_showButton
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: showButton
    - secretKey: Accounts_OAuth_Custom_tokenPath
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: tokenPath
    - secretKey: Accounts_OAuth_Custom_tokenSentVia
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: tokenSentVia
    - secretKey: Accounts_OAuth_Custom_usernameField
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /rocketchat/config/oidc
          metadataPolicy: None
          property: usernameField

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rocketchat-mongodb-uri-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: mongo-uri
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/mongodb
        metadataPolicy: None
        property: mongo-uri
    - secretKey: mongo-oplog-uri
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/mongodb
        metadataPolicy: None
        property: mongo-oplog-uri

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rocketchat-mongodb-auth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: mongodb-passwords
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/mongodb
        metadataPolicy: None
        property: mongodb-passwords
    - secretKey: mongodb-root-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/mongodb
        metadataPolicy: None
        property: mongodb-root-password
    - secretKey: mongodb-metrics-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/mongodb
        metadataPolicy: None
        property: mongodb-metrics-password
    - secretKey: mongodb-replica-set-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/mongodb
        metadataPolicy: None
        property: mongodb-replica-set-key
