apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rocketchat-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/admin
        metadataPolicy: None
        property: ADMIN_USERNAME
    - secretKey: ADMIN_NAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/admin
        metadataPolicy: None
        property: ADMIN_NAME
    - secretKey: ADMIN_PASS
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/admin
        metadataPolicy: None
        property: ADMIN_PASS
    - secretKey: ADMIN_EMAIL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /rocketchat/config/admin
        metadataPolicy: None
        property: ADMIN_EMAIL
