apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: HOMEPAGE_VAR_SYNOLOGY_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /homepage/config
        property: HOMEPAGE_VAR_SYNOLOGY_PASSWORD
    - secretKey: HOMEPAGE_VAR_UNIFI_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /homepage/config
        property: HOMEPAGE_VAR_UNIFI_PASSWORD
    - secretKey: HOMEPAGE_VAR_LIDARR_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /homepage/config
        property: HOMEPAGE_VAR_LIDARR_KEY
