homepage:
  deployment:
    replicas: 1
    envFrom:
      - secretRef:
          name: homepage-front-key-secret
  ingressRoute:
    host: homepage.alexlebens.net
    authentik:
      outpost: authentik-outpost-proxy
  config:
    widgets:
      - logo:
          icon: https://gitea.alexlebens.net/alexlebens/icons/raw/branch/main/alexlebensnet-icon_white.png
      - datetime:
          text_size: xl
          format:
            dateStyle: long
            timeStyle: short
            hour12: false
      - openmeteo:
          label: Denver
          latitude: 39.73
          longitude: 104.99
          units: metric
          cache: 5
    services:
      - Media:
          - Plex:
              icon: plex.png
              href: https://plex.alexlebens.net
              description: Media server
              siteMonitor: http://plex.plex:32400
              statusStyle: dot
          - Overseerr:
              icon: overseerr.png
              description: Requests
              href: https://overseerr.alexlebens.net
              siteMonitor: http://overseerr.overseerr:5055
              statusStyle: dot
              widget:
                type: overseerr
                url: http://overseerr.overseerr:5055
                key: '{{HOMEPAGE_VAR_OVERSEERR_KEY}}'
          - Jellyfin:
              icon: jellyfin.png
              description: Media server
              href: https://jellyfin.alexlebens.net/
              siteMonitor: http://jellyfin.jellyfin:8096
              statusStyle: dot
          - TubeAchivist:
              icon: tube-archivist.png
              description: Youtube downloader
              href: https://tubearchivist.alexlebens.net/login/
              siteMonitor: http://tubearchivist.tubearchivist:8000
              statusStyle: dot
          - Navidrome:
              icon: navidrome.png
              description: Music
              href: https://navidrome.alexlebens.net
              siteMonitor: http://navidrome.navidrome:4533
              statusStyle: dot
          - Audiobookshelf:
              icon: audiobookshelf.png
              description: Audiobooks, Books, and Podcasts
              href: https://audiobookshelf.alexlebens.net
              siteMonitor: http://audiobookshelf.audiobookshelf:80
              statusStyle: dot
          - Calibre:
              icon: calibre-web.png
              description: Books
              href: https://calibre.alexlebens.net
              siteMonitor: http://calibre-web.calibre-web:8083
              statusStyle: dot
      - Applications:
          - Home Assistant:
              icon: home-assistant.png
              description: Home automation
              href: https://homeassistant.alexlebens.net
              siteMonitor: http://home-assistant.home-assistant:8123
              statusStyle: dot
          - Vikunja:
              icon: vikunja.png
              description: Notes and tasks
              href: https://vikunja.alexlebens.net
              siteMonitor: http://vikunja-frontend.vikunja:80
              statusStyle: dot
          - Outline:
              icon: outline.png
              description: Wiki
              href: https://outline.alexlebens.net
              siteMonitor: http://outline.outline:3000
              statusStyle: dot
          - Rss:
              icon: freshrss.svg
              description: Rss reader
              href: https://rss.alexlebens.net
              siteMonitor: http://freshrss.freshrss:80
              statusStyle: dot
    settings:
      favicon: https://gitea.alexlebens.net/alexlebens/icons/raw/branch/main/alexlebensnet-icon_white.png
      headerStyle: clean
      background:
        image: https://w.wallhaven.cc/full/6d/wallhaven-6d7xyq.jpg
        brightness: 50
      cardBlur: md
      theme: dark
      disableCollapse: true
