outline:
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    host: outline.alexlebens.net
  persistence:
    type: s3
    s3:
      credentialsSecret: outline-bucket-auth-secret
      endpointConfigMap:
        enabled: false
      region: nyc3
      bucketName: alexlebens-net-outline
      host: alexlebens-net.nyc3.digitaloceanspaces.com
      urlProtocol: https
  outline:
    url: https://outline.alexlebens.net
    secretKey:
      existingSecretName: outline-key-secret
      existingSecretKey: secret-key
    utilsSecret:
      existingSecretName: outline-key-secret
      existingSecretKey: utils-key
    database:
      usernameSecret:
        existingSecretName: postgresql-outline-cluster-app
        existingSecretKey: username
      passwordSecret:
        existingSecretName: postgresql-outline-cluster-app
        existingSecretKey: password
      databaseName:
        existingSecretName: postgresql-outline-cluster-app
        existingSecretKey: dbname
      databaseHost:
        existingSecretName: postgresql-outline-cluster-app
        existingSecretKey: host
      databasePort:
        existingSecretName: postgresql-outline-cluster-app
        existingSecretKey: port
    auth:
      oidc:
        enabled: true
        clientId:
          existingSecretName: outline-oidc-secret
          existingSecretKey: client
        clientSecret:
          existingSecretName: outline-oidc-secret
          existingSecretKey: secret
        authUri: https://authentik.alexlebens.net/application/o/authorize/
        tokenUri: https://authentik.alexlebens.net/application/o/token/
        userinfoUri: https://authentik.alexlebens.net/application/o/userinfo/
        usernameClaim: email
        displayName: Authentik
        scopes: openid profile email
postgres-cluster:
  cluster:
    name: cl01tl
    image:
      repository: ghcr.io/cloudnative-pg/postgresql
      tag: 16.2
    instances: 2
    storage:
      data:
        storageClass: ceph-block
        size: 10Gi
      wal:
        storageClass: ceph-block
        size: 2Gi
  bootstrap:
    recoveryEnabled: false
    recoveryIndex: 1
    endpointURL: https://nyc3.digitaloceanspaces.com
    bucket: alexlebens-net
  backup:
    backupEnabled: true
    backupIndex: 1
    endpointURL: https://nyc3.digitaloceanspaces.com
    bucket: alexlebens-net
