calibre-server:
  deployment:
    env:
      TZ: US/Mountain
  ingressRoute:
    enabled: true
    http:
      host: calibre-server.alexlebens.net
    authentik:
      outpost: authentik-proxy-outpost      
  persistence:
    config:
      storageClassName: ceph-block
      storageSize: 5Gi
    books:
      claimName: calibre-server-nfs-storage
      nfs:
        path: /volume2/Storage/Calibre
        server: synologybond.alexlebens.net
