apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketchat-mongodb-fix-clustermonitor-role-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rocketchat-mongodb-fix-clustermonitor-role-configmap
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
data:
  user_set_role_clusterMonitor.sh: |
    #! /bin/bash

    # #include <everything>
    source /opt/bitnami/scripts/libmongodb.sh

    main() {
      local cmd="
        db.getSiblingDB('rocketchat').grantRolesToUser('rocketchat',[{ role: 'clusterMonitor", db: 'rocketchat' }])
        db.getSiblingDB('rocketchat').grantRolesToUser('rocketchat',[{ role: 'clusterMonitor', db: 'rocketchat' }])
      "
    }

    main
