apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-object-store
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rook-ceph-object-store
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - s3.alexlebens.net
      secretName: rook-ceph-object-store-secret-tls
  rules:
    - host: s3.alexlebens.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rook-ceph-rgw-ceph-object-store
                port:
                  name: http
