rocketchat:
  host: rocketchat.alexlebens.net
  extraEnv:
    - name: MONGO_URL
      valueFrom:
        secretKeyRef:
          name: rocket-chat-mongodb-connection
          key: MONGO_URL
    - name: MONGO_OPLOG_URL
      valueFrom:
        secretKeyRef:
          name: rocket-chat-mongodb-connection
          key: MONGO_OPLOG_URL
    - name: ADMIN_USERNAME
      valueFrom:
        secretKeyRef:
          name: rocket-chat-admin-secret
          key: ADMIN_USERNAME
    - name: ADMIN_NAME
      valueFrom:
        secretKeyRef:
          name: rocket-chat-admin-secret
          key: ADMIN_NAME
    - name: ADMIN_PASS
      valueFrom:
        secretKeyRef:
          name: rocket-chat-admin-secret
          key: ADMIN_PASS
    - name: ADMIN_EMAIL
      valueFrom:
        secretKeyRef:
          name: rocket-chat-admin-secret
          key: ADMIN_EMAIL
  mongodb:
    enabled: false
    service:
      ports:
        mongodb: 60000
    auth:
      rootPassword: "notapassword"
      passwords:
        - "notapassword"
  persistence:
    enabled: true
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 10Gi
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    path: /
    tls:
      - secretName: rocket-chat-secret-tls
        hosts:
          - rocketchat.alexlebens.net
    federation:
      serveWellKnown: true
  prometheusScraping:
    enabled: true
  serviceMonitor:
    enabled: true
mongodb:
  architecture: standalone
  auth:
    enabled: true
    rootUser: root
    usernames:
      - rocketchat
    databases:
      - rocketchat
    existingSecret: rocket-chat-mongodb-passwords
  replicaCount: 1
  pdb:
    minAvailable: 0
  persistence:
    enabled: true
    storageClass: ceph-block
    size: 10Gi
  backup:
    enabled: true
    cronjob:
      schedule: "@daily"
      storage:
        storageClass: nfs-client
        size: 10Gi
  volumePermissions:
    enabled: true
  arbiter:
    enabled: false
    pdb:
      minAvailable: 0
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
