apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-synapse-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: signing_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/key
        metadataPolicy: None
        property: signing_key
    - secretKey: registration_shared_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/key
        metadataPolicy: None
        property: registration_shared_secret
    - secretKey: macaroon_secret_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/key
        metadataPolicy: None
        property: macaroon_secret_key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-synapse-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: redis-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/config
        metadataPolicy: None
        property: redis-password
    - secretKey: oidc.yaml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/config
        metadataPolicy: None
        property: oidc.yaml
    - secretKey: config.yaml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/config
        metadataPolicy: None
        property: config.yaml

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-hookshot-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: config.yml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/hookshot
        metadataPolicy: None
        property: config
    - secretKey: registration.yml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/hookshot
        metadataPolicy: None
        property: registration
    - secretKey: hookshot-registration.yaml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/hookshot
        metadataPolicy: None
        property: registration        
    - secretKey: passkey.pem
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/hookshot
        metadataPolicy: None
        property: passkey

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-matrix-synapse-cluster-backup-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-net/auth
        metadataPolicy: None
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-net/auth
        metadataPolicy: None
        property: ACCESS_SECRET_KEY
