operator:
  console:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      tls:
        - secretName: minio-secret-tls
          hosts:
            - minio.alexlebens.net
      host: console.local
      path: /
      pathType: Prefix
      number: 9090
