apiVersion: v2
name: homarr
version: 0.0.1
home:
sources:
  - https://github.com/ajnart/homarr
  - https://oben01.github.io/charts/charts/homarr/
dependencies:
  - name: homarr
    version: 1.2.2
    repository: https://oben01.github.io/charts/
appVersion: v0.15.2
