gitea:
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts:
      - host: gitea.alexlebens.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-secret-tls
        hosts:
          - gitea.alexlebens.net
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://gitea.alexlebens.net
        ENABLE_PPROF: true
      webhook:
        ALLOWED_HOST_LIST: private
        scopes: email profile
      service:
        DISABLE_REGISTRATION: true
        SHOW_REGISTRATION_BUTTON: false
        explore:
          REQUIRE_SIGNIN_VIEW: true
      database:
        DB_TYPE: postgres
        SCHEMA: public
    additionalConfigFromEnvs:
      - name: GITEA__DATABASE__HOST
        valueFrom:
          secretKeyRef:
            name: postgresql-gitea-cluster-app
            key: host
      - name: GITEA__DATABASE__NAME
        valueFrom:
          secretKeyRef:
            name: postgresql-gitea-cluster-app
            key: dbname
      - name: GITEA__DATABASE__USER
        valueFrom:
          secretKeyRef:
            name: postgresql-gitea-cluster-app
            key: user
      - name: GITEA__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: postgresql-gitea-cluster-app
            key: password
    oauth:
      - name: Authentik
        provider: openidConnect
        existingSecret: gitea-oidc-secret
        autoDiscoverUrl: "https://authentik.alexlebens.net/application/o/gitea/.well-known/openid-configuration"
        iconUrl: https://goauthentik.io/img/icon.png
        scopes: "email profile"
  persistence:
    storageClass: ceph-block
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false
  redis-cluster:
    enabled: true
postgres-cluster:
  cluster:
    name: cl01tl
    image:
      repository: ghcr.io/cloudnative-pg/postgresql
      tag: 16.2
    instances: 3
    storage:
      data:
        storageClass: ceph-block
        size: 10Gi
      wal:
        storageClass: ceph-block
        size: 2Gi
  bootstrap:
    recoveryEnabled: false
    recoveryIndex: 4
    endpointURL: https://nyc3.digitaloceanspaces.com
    bucket: alexlebens-net
  backup:
    backupEnabled: true
    backupIndex: 4
    endpointURL: https://nyc3.digitaloceanspaces.com
    bucket: alexlebens-net
