apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-server"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /authentik/oidc/argocd
        metadataPolicy: None
        property: secret
    - secretKey: client
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /authentik/oidc/argocd
        metadataPolicy: None
        property: client

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-cluster-cl02do-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-server"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  target:
    name: argocd-cluster-cl02do-secret
    template:
      engineVersion: v2
      templateFrom:
      - target: Annotations
        literal: "argocd.argoproj.io/secret-type: cluster"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: name
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /argocd/credentials/cluster/cl02do
        metadataPolicy: None
        property: name
    - secretKey: server
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /argocd/credentials/cluster/cl02do
        metadataPolicy: None
        property: server
    - secretKey: config
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /argocd/credentials/cluster/cl02do
        metadataPolicy: None
        property: config
