apiVersion: v2
name: vikunja
version: 0.0.3
sources:
  - https://kolaente.dev/vikunja/vikunja
  - https://kolaente.dev/vikunja/helm-chart
  - https://github.com/alexlebens/helm-charts/charts/postgres-cluster
dependencies:
  - name: my-vikunja
    version: 0.4.3
    repository: oci://kolaente.dev/vikunja/vikunja
  - name: postgres-cluster
    version: 0.2.3
    repository: http://alexlebens.github.io/helm-charts
appVersion: v0.21.1
