apiVersion: v2
name: vikunja
version: 1.0.0
sources:
  - https://kolaente.dev/vikunja/vikunja
  - https://kolaente.dev/vikunja/helm-chart
  - https://github.com/alexlebens/helm-charts/charts/postgres-cluster
dependencies:
  - name: vikunja
    version: 0.4.3
    repository: oci://kolaente.dev/vikunja
  - name: postgres-cluster
    alias: postgres-16-cluster
    version: 2.4.2
    repository: http://alexlebens.github.io/helm-charts
  - name: redis
    version: 19.1.2
    repository: https://charts.bitnami.com/bitnami
appVersion: v0.21.1
