{{- if .Values.application.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    app.kubernetes.io/name: stack
    app.kubernetes.io/instance: stack
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: stack
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm  
spec:
  project: default
  source:
    repoURL: {{ .Values.application.source.repo }}
    targetRevision: {{ .Values.application.source.revision }}        
    path: {{ .Values.application.source.path }}
  destination:
    name: in-cluster
    namespace: {{ .Release.Namespace }}
  revisionHistoryLimit: 3
  syncPolicy:
    {{- toYaml .Values.application.syncPolicy | nindent 4 }}
{{- end }}
