apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "stack"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm  
spec:
  project: default
  source:
    path: clusters/cl01tl/deployment/stack
    repoURL: git@github.com:alexlebens/alexlebns-net.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: {{ .Release.Namespace }}
  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    retry:
      limit: 10
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - PruneLast=true
