apiVersion: v2
name: taiga
version: 1.0.0
sources:
  - https://github.com/taigaio
  - https://github.com/rabbitmq/rabbitmq-server
  - https://github.com/alexlebens/helm-charts/charts/taiga
  - https://github.com/alexlebens/helm-charts/charts/postgres-cluster
dependencies:
  - name: taiga
    version: 0.1.4
    repository: http://alexlebens.github.io/helm-charts
  - name: postgres-cluster
    version: 2.2.0
    repository: http://alexlebens.github.io/helm-charts
appVersion: 6.7.7
