git:
  repo: git@github.com:alexlebens/alexlebens-net.git
  revision: HEAD
  path: clusters/cl01tl
applicationSet:
  - name: applications
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: deployment
    namespace: argocd
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: platform
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: services
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: storage
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=false
        - PruneLast=true
application:
  stack:
    namespace: argocd
    source:
      repo: git@github.com:alexlebens/alexlebens-net.git
      revision: HEAD
      path: deployment/stack
    syncPolicy:
      automated:
        prune: true
        selfHeal: false
      retry:
        limit: 10
        backoff:
          duration: 1m
          factor: 2
          maxDuration: 16m
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=false
        - ServerSideApply=true
        - PruneLast=true
  cilium:
    namespace: kube-system
    source:
      repo: git@github.com:alexlebens/alexlebens-net.git
      revision: HEAD
      path: standalone/cilium
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      retry:
        limit: 10
        backoff:
          duration: 1m
          factor: 2
          maxDuration: 16m
      syncOptions:
        - CreateNamespace=false
        - ApplyOutOfSyncOnly=false
        - ServerSideApply=true
        - PruneLast=true
  metricsServer:
    namespace: kube-system
    source:
      repo: git@github.com:alexlebens/alexlebens-net.git
      revision: HEAD
      path: standalone/metrics-server
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      retry:
        limit: 10
        backoff:
          duration: 1m
          factor: 2
          maxDuration: 16m
      syncOptions:
        - CreateNamespace=false
        - ApplyOutOfSyncOnly=false
        - ServerSideApply=true
        - PruneLast=true
