git:
  repo: git@github.com:alexlebens/alexlebens-net.git
  revision: HEAD
  path: clusters/cl01tl
applicationSet:
  - name: applications
    syncPolicy:
      automated:
        enabled: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: deployment
    namespace: argocd
    syncPolicy:
      automated:
        enabled: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: platform
    syncPolicy:
      automated:
        enabled: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: services
    syncPolicy:
      automated:
        enabled: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: storage
    syncPolicy:
      automated:
        enabled: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
