freshrss:
  image:
    repository: ghcr.io/linuxserver/freshrss
    tag: 1.23.1
  env:
    TZ: US/Mountain
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - host: rss.alexlebens.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: freshrss-secret-tls
          hosts:
            - rss.alexlebens.net
  persistence:
    config:
      enabled: true
