freshrss:
  deployment:
    env:
      TZ: US/Mountain
      OIDC_ENABLED: 1
      OIDC_PROVIDER_METADATA_URL: https://authentik.alexlebens.net/application/o/freshrss/.well-known/openid-configuration
      OIDC_X_FORWARDED_HEADERS: X-Forwarded-Port X-Forwarded-Proto X-Forwarded-Host
      OIDC_SCOPES: openid email profile
      OIDC_REMOTE_USER_CLAIM: preferred_username
    envFrom:
      - secretRef:
          name: freshrss-oidc-secret
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    host: rss.alexlebens.net
  persistence:
    config:
      storageClassName: ceph-block
      storageSize: 5Gi
postgres-cluster:
  cluster:
    name: cl01tl
    image:
      repository: ghcr.io/cloudnative-pg/postgresql
      tag: 16.2
    instances: 2
    storage:
      data:
        storageClass: ceph-block
        size: 10Gi
      wal:
        storageClass: ceph-block
        size: 2Gi
  bootstrap:
    recoveryEnabled: false
    recoveryIndex: 1
    endpointURL: https://nyc3.digitaloceanspaces.com
    bucket: alexlebens-net
  backup:
    backupEnabled: true
    backupIndex: 1
    endpointURL: https://nyc3.digitaloceanspaces.com
    bucket: alexlebens-net
postgres-16-cluster:
  mode: replica
  kubernetesClusterName: cl01tl
  cluster:
    walStorage:
      storageClass: local-path
    storage:
      storageClass: local-path
    monitoring:
      enabled: true
  replica:
    importType: microservice
    importDatabases:
      - app
    externalCluster:
      connectionParameters:
        host: postgresql-freshrss-cluster-rw
        user: app
        dbname: app
      password:
        name: postgresql-freshrss-cluster-app
        key: password
  backup:
    enabled: true
    endpointURL: https://nyc3.digitaloceanspaces.com
    endpointBucket: alexlebens-net
    endpointCredentials: freshrss-postgresql-16-cluster-backup-secret
    backupIndex: 1
    retentionPolicy: "14d"
