apiVersion: v2
name: argo
version: 0.1.0
home: https://outline.alexlebens.net/doc/argo-cd-qLEdrgdwOD
sources:
  - https://github.com/argoproj/argo-cd
dependencies:
  - name: argo-cd
    version: 6.4.1
    repository: https://argoproj.github.io/argo-helm
appVersion: v2.10.1
