apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: outline-bucket
  namespace: rook-ceph
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  generateBucketName: outline-bucket
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: 2000
    maxSize: 20G
