apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
