apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-tailscale
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault-tailscale
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
      - vault-internal.alexlebens.net
      secretName: vault-tailscale-secret-tls
  rules:
    - host: vault-internal.alexlebens.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-internal
                port:
                  name: https-internal
