apiVersion: v1
kind: Service
metadata:
  name: tailscale-cl01tl-vault
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tailscale-cl01tl-vault
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 8200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
