apiVersion: v2
name: loki
version: 1.0.0
sources:
  - https://github.com/grafana/loki
  - https://github.com/grafana/helm-charts
dependencies:
  - name: loki
    version: 5.43.7
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.15.5
    repository: https://grafana.github.io/helm-charts
appVersion: v2.9.5
